# Data setup (step 1)
data_dir: /vols/cms/jl3222/nsbi_photon_final_state/data
morphing_setup: /vols/cms/jl3222/nsbi_photon_final_state/data/setup.h5

# Step 2: MadGraph generation
madgraph:
  dir: /vols/cms/jl3222/software/mg5amcnlo_3p5p1/MG5_aMC_v3_5_1
  test_run: false             # ←←← 关键行，告诉脚本只跑一次（测试用）
  n_runs: 2                 # 先小跑；稳定后再加大
  output_dir: /vols/cms/jl3222/nsbi_photon_final_state/02_mg_processes
  energy: 14                # HL-LHC=14；未来可切到100

# Step 3: Delphes
delphes:
  # 与 Step2 的输出保持一致（非常关键）
  input_dir_prefix: /vols/cms/jl3222/nsbi_photon_final_state/02_mg_processes
  output_file: /vols/cms/jl3222/nsbi_photon_final_state/04_post_delphes/delphes
  # 合并/长期保存处（03b_compile.py 使用）
  long_term_storage_dir: /vols/cms/jl3222/nsbi_photon_final_state/04_post_delphes

# Step 4: Sampling
sampling:
  input_dir: /vols/cms/jl3222/nsbi_photon_final_state/04_post_delphes
  output_dir: /vols/cms/jl3222/nsbi_photon_final_state/05_samples

# Plotting
plotting:
  fancy_name:
    c0: $c_{\phi}$
    c1: $c_{\phi d}$
    c2: $c_{t \phi}$
  color:
    c0: red
    c1: blue
    c2: green
